DROP PROCEDURE IF EXISTS historico_compra;
CREATE PROCEDURE historico_compra(
  
)
BEGIN
    --
    
END$$
DELIMITER ;

/*
1. CREAR UNA FUNCION QUE MUESTRE EL HISTORICO DE
   COMPRA DE CADA CLIENTE
   CLIENTE | PRODUCTO | MONTO COMPRADO